version: "3.9"

services:
  auth-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "${AUTH_DB_HOST_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USER} -d ${AUTH_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [internal]
    volumes:
      - authdb_data:/var/lib/postgresql/data

  products-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${PRODUCTS_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCTS_DB_PASSWORD}
      POSTGRES_DB: ${PRODUCTS_DB_NAME}
    ports:
      - "${PRODUCTS_DB_HOST_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PRODUCTS_DB_USER} -d ${PRODUCTS_DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [internal]
    volumes:
      - productsdb_data:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    depends_on:
      auth-db:
        condition: service_healthy
    networks: [internal]
    expose:
      - "3000"

  products-service-1:
    build: ./products-service
    env_file:
      - ./products-service/.env
    depends_on:
      products-db:
        condition: service_healthy
    networks: [internal]
    expose:
      - "3000"

  products-service-2:
    build: ./products-service
    env_file:
      - ./products-service/.env
    depends_on:
      products-db:
        condition: service_healthy
    networks: [internal]
    expose:
      - "3000"

  products-lb:
    build: ./nginx-lb
    ports:
      - "${LB_PORT}:80"
    depends_on:
      - products-service-1
      - products-service-2
    networks: [internal]

  api-gateway:
    build: ./api-gateway
    env_file:
      - ./api-gateway/.env
    environment:
      PORT: ${GATEWAY_PORT}
    ports:
      - "${GATEWAY_PORT}:3000"
    depends_on:
      - auth-service
      - products-lb
    networks: [internal]

networks:
  internal:
    driver: bridge

volumes:
  authdb_data:
  productsdb_data:
